<?php

return [
    'jenis_usaha' => [
        'Konstruksi',
        'Konsultan Konstruksi',
    ],

    'regions' => [
        'KALIMANTAN TIMUR' => [
            'KOTA SAMARINDA',
            'KOTA BALIKPAPAN',
            'KOTA BONTANG',
            'KABUPATEN BERAU',
            'KABUPATEN KUTAI BARAT',
            'KABUPATEN KUTAI KARTANEGARA',
            'KABUPATEN KUTAI TIMUR',
            'KABUPATEN MAHAKAM ULU',
            'KABUPATEN PASER',
            'KABUPATEN PENAJAM PASER UTARA',
        ],
    ],

    'header_aliases' => [
        'id_izin' => ['id_izin', 'id izin', 'id_perizinan', 'nomor_izin'],
        'nib' => ['nib', 'nomor_induk_berusaha'],
        'npwp' => ['npwp', 'npwp_bujk'],
        'asosiasi' => ['asosiasi', 'asosiasi_perusahaan'],
        'nama_bu' => ['nama_bu', 'nama_bujk', 'bujk', 'nama_perusahaan', 'nama_badan_usaha'],
        'bentuk_usaha' => ['bentuk_usaha', 'bentuk usaha'],
        'alamat' => ['alamat', 'alamat_bujk'],
        'telepon' => ['telepon', 'telp', 'telp_bujk', 'no_telp', 'nomor_telp', 'nomor_telepon', 'kontak'],
        'email' => ['email', 'email_bujk'],
        'website' => ['website', 'website_bujk', 'web', 'situs', 'url'],
        'faksimili' => ['faksimili', 'fax', 'faks', 'faximile'],
        'propinsi' => ['propinsi', 'provinsi', 'provinsi_bujk'],
        'kabupaten' => ['kabupaten', 'kab_kota', 'kab_kota_bujk', 'kabupaten_kota', 'kota_kabupaten', 'kab/kota'],
        'jenis_usaha' => ['jenis_usaha', 'jenis_bujk', 'jenis_usaha_bujk'],
        'sifat' => ['sifat'],
        'kbli_bener' => ['kbli_bener', 'kbli benar', 'kbli_final'],
        'kbli_inputan' => ['kbli_inputan', 'kbli inputan', 'kbli_input'],
        'ket_kbli' => ['ket_kbli', 'keterangan_kbli', 'keterangan kbli'],
        'bentuk_badan_usaha' => ['bentuk_badan_usaha', 'bentuk badan usaha'],
        'klasifikasi' => ['klasifikasi'],
        'kode_subklasifikasi' => ['kode_subklasifikasi', 'kode subklasifikasi', 'kode_sub_klasifikasi'],
        'subklasifikasi' => ['subklasifikasi', 'sub_klasifikasi', 'sub klasifikasi', 'subklasifikasi_usaha'],
        'id_kualifikasi' => ['id_kualifikasi', 'id kualifikasi', 'kualifikasi'],
        'pelaksana_sertifikasi' => ['pelaksana_sertifikasi', 'pelaksana sertifikasi', 'lsbu_penerbit', 'lsbu/penerbit'],
        'tanggal_ditetapkan' => ['tanggal_ditetapkan', 'tanggal ditetapkan', 'tanggal_terbit', 'tanggal terbit'],
        'tanggal_masa_berlaku' => ['tanggal_masa_berlaku', 'tanggal masa berlaku', 'masa_berlaku'],
        'valid' => ['valid'],
        'tgl_update' => ['tgl_update', 'tanggal_update', 'tanggal update'],
        'nama_pjbu' => ['nama_pjbu', 'nama pjbu'],
        'nik_pjbu' => ['nik_pjbu', 'nik pjbu'],
        'npwp_pjbu' => ['npwp_pjbu', 'npwp pjbu'],
        'jenis_perubahan' => ['jenis_perubahan', 'jenis perubahan'],
        'last_perubahan_at' => ['last_perubahan_at', 'last perubahan at', 'perubahan_terakhir'],
        'deskripsi_klasifikasi' => ['deskripsi_klasifikasi', 'deskripsi klasifikasi'],
        'status' => ['status'],
        'negara_asal' => ['negara_asal', 'negara asal'],
        'nama_pjtbu' => ['nama_pjtbu', 'nama pjtbu'],
        'nama_pjskbu' => ['nama_pjskbu', 'nama pjskbu'],
        'nama_pjskbu_2' => ['nama_pjskbu_2', 'nama pjskbu 2', 'nama_pjskbu2'],
        'id_asosiasi' => ['id_asosiasi', 'id asosiasi'],
    ],
];